name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install Clasp
      run: npm install -g @google/clasp
      
    - name: Create clasprc.json
      run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json
    
    - name: Update clasp.json with Script ID
      run: sed -i 's/SCRIPT_ID_PLACEHOLDER/${{ secrets.SCRIPT_ID }}/g' clasp.json
    
    - name: List files
      run: ls -la
    
    - name: List src directory
      run: ls -la src
      
    - name: Deploy with Clasp
      run: clasp push -f
