name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install Clasp
      run: npm install -g @google/clasp
      
    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        
    - name: Setup authentication
      run: |
        echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json
        clasp login --status
        
    - name: Setup script ID
      run: |
        echo '{"scriptId":"${{ secrets.SCRIPT_ID }}","rootDir":"src"}' > clasp.json
        cat clasp.json
        
    - name: Push to Apps Script
      run: clasp push
